print("="*50)
line1=input("enter 1 line of text:")
line2=input("enter 2 line of text:")
print("="*50)
print(line1)
print(line2)
l1=line1.split()
l2=line2.split()
s1=set(l1)
s2=set(l2)
s3=s1.intersection(s2)
print("common word in line1 and line two:{}".format(s3))
print("common word length  in line1 and line two:{}".format(len(s3)))
