print("="*100)
eno=int(input("enter the employee number:"))
ename=input("enter the empoylee name:")
basicsal=float(input("enter the basic sal for empoylee:"))
cname=input("enter the company name of the empoylee:")
print("="*100)
if basicsal<0:
    print("{} is invalid salary".format(basicsal))
elif (basicsal>=10000):
    ta=basicsal*(10/100)
    da=basicsal*(20/100)
    hra=basicsal*(16/100)
    ma=basicsal*(2/100)
    lic=basicsal*(1/100)
    gpf=basicsal*(1/100)
else:
    ta=basicsal*(5/100)
    da=basicsal*(10/100)
    hra=basicsal*(8/100)
    ma=basicsal*(2/100)
    lic=basicsal*(0.5/100)
    gpf=basicsal*(1/100)
net_sal=(basicsal+ta+da+hra+ma)-(lic+gpf)
print("="*100)
print("\tempoylee pay slip")
print("="*100)
print("empoylee no:{}".format(eno))
print("empoylee name:{}".format(ename))
print("empoylee company name:{}".format(cname))
print("empoylee basicsal:{}".format(basicsal))
print("empoylee ta:{}".format(ta))
print("empoylee da:{}".format(da))
print("empoylee hra:{}".format(hra))
print("empoylee ma:{}".format(ma))
print("empoylee deductions")
print(" empoylee lic:{}".format(lic))
print("empoylee gpf:{}".format(gpf))
print("="*100)
print("\tempoylee net salary:{}".format(net_sal))
print("="*100)


