print("*"*50)
print("\tArthimatic operators")
print("*"*50)
a=float(input("enter the value a:"))
b=float(input("enter the value b:"))
print("value of a--->({}): value of b--->({})".format(a,b))
print("\t sum(a,b)={}".format(a+b))
print("\t sub(a,b)={}".format(a-b))
print("\t mul(a,b)={}".format(a*b))
print("\t div(a,b)={}".format(a/b))
print("\t f.div(a,b)={}".format(a//b))
print("\t mod(a,b)={}".format(a%b))
print("\t pow(a,b)={}".format(a**b))
print("*"*50)
#roots logic
print("roots logic")
a=int(input("enter the val of a to be square:"))
s=a**0.5
print("the square of {}-->{}".format(a,s))
c=a**(1/3)
print("the cube root {}--->{}".format(a,c))
s1=int(input("enter the squ-n of the number"))
c1=int(input("enter the cube root of-m number:"))
d=a*(s1/c1)
print("root==>",d)
print("__"*50)
#(a+b)**2
a=int(input("enter the a val:"))
b=int(input("enter the b val:"))
print("(a+b)**2={}".format((a+b)**2))